
import algoritmos.Mandelbrot;
import algoritmos.IFractal;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Event;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.InputEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.SwingUtilities;
import javax.swing.event.MouseInputAdapter;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Cinthia
 */
public class Fractal extends javax.swing.JPanel {

    private Color[] colors = new Color[128];
    private double viewX = 0.0;
    private double viewY = 0.0;
    private double zoom = 1.0;
    private int mouseX;
    private int mouseY;
    private boolean editable = true;
    private IFractal calculoFractal = new Mandelbrot();
    private BufferedImage biImagen;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Crea un nuevo fractal
     */
    public Fractal() {
        initComponents();

        init();
    }

    
    
    /**
     * @return the zoom
     */
    public double getZoom() {
        return zoom;
    }

    /**
     * @param zoom the zoom to set
     */
    public void setZoom(double zoom) {
        this.zoom = zoom;
    }

    /**
     * @param maxIteraciones Número máximo de iteraciones
     */
    public void setMaxIteraciones(int maxIteraciones) {
        if (calculoFractal != null) {
            calculoFractal.setMaxIteraciones(maxIteraciones);
        }
    }

    /**
     * @return El númeo máximo de iteraciones
     */
    public int getMaxIteraciones() {
        return calculoFractal == null ? 0 : calculoFractal.getMaxIteraciones();
    }

    /**
     * @return El punto X inicial de visualización del fractal
     */
    public double getViewX() {
        return viewX;
    }

    /**
     * @param viewX Asigna el punto X inicial de visualización del fractal
     */
    public void setViewX(double viewX) {
        this.viewX = viewX;
    }

    /**
     * @return el punto Y inicial de visualización del fractal
     */
    public double getViewY() {
        return viewY;
    }

    /**
     * @param viewY Asigna el punto Y inicial de visualización del fractal
     */
    public void setViewY(double viewY) {
        this.viewY = viewY;
    }

    /**
     * @param editable Habilita la posibilidad de mover el fractal o hacer zoom
     */
    public void setEditable(boolean editable) {
        this.editable = editable;
    }

    /**
     * @return La posibilidad de mover el fractal o hacer zoom
     */
    public boolean getEditable() {
        return this.editable;
    }

    @Override
    public void setBounds(int x, int y, int width, int height) {
        super.setBounds(x, y, width, height); //To change body of generated methods, choose Tools | Templates.
        if (java.beans.Beans.isDesignTime()) {
            return;
        }
        if (width > 0 && height > 0) {
            // Al redimensionar el control, inicializa un nuevo buffer para almacenar el fractal
            biImagen = new BufferedImage(width, height, BufferedImage.TYPE_INT_BGR);
        }
    }

    @Override
    public void setBounds(Rectangle r) {
        super.setBounds(r); //To change body of generated methods, choose Tools | Templates.
        if (java.beans.Beans.isDesignTime()) {
            return;
        }
        if (r.width > 0 && r.height > 0) {
            // Al redimensionar el control, inicializa un nuevo buffer para almacenar el fractal
            biImagen = new BufferedImage(r.width, r.height, BufferedImage.TYPE_INT_BGR);
        }
    }

    /**
     * Devuelve el tipo de fractal (Mandelbrot, Julia, etc.)
     * @return tipo de fractal
     */
    public IFractal getTipoFractal() {
        return calculoFractal;
    }

    /**
     * Asigna el tipo de fractal a mostrar
     * @param tipoFractal Tipo de fractal a asignar
     */
    public void setTipoFractal(IFractal tipoFractal) {
        this.calculoFractal = tipoFractal;
    }

    /**
     * Inicialización adicional del control
     */
    public void init() {
        // Genera paleta de colores
        for (int i = 0; i < colors.length; i++) {
            int c = 2 * i * 256 / colors.length;
            if (c > 255) {
                c = 511 - c;
            }
            colors[i] = new Color(c, c, c);
        }
        
        addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                // Punto inicial para luego dibujar el recuadro
                mouseX = e.getX();  
                mouseY = e.getY();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                int x = e.getX();
                int y = e.getY();
                if (!editable) {
                    return;
                }
                if ((e.getModifiers() & InputEvent.BUTTON1_MASK) != 0) {
                    if (x != mouseX && y != mouseY) {
                        int w = getSize().width;
                        int h = getSize().height;
                        viewX += getZoom() * Math.min(x, mouseX) / Math.min(w, h);
                        viewY += getZoom() * Math.min(y, mouseY) / Math.min(w, h);
                        setZoom(getZoom() * Math.max((double) Math.abs(x - mouseX) / w, (double) Math.abs(y - mouseY) / h));
                        /*                        int maxIteraciones = calculoFractal.getMaxIteraciones(); // Si queremos añadir más detalle con cada zoom
                        maxIteraciones += maxIteraciones / 4;
                        calculoFractal.setMaxIteraciones(maxIteraciones);*/
                        repaint();
                    }
                } else if ((e.getModifiers() & InputEvent.BUTTON3_MASK) != 0) {
                }

            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });

        addMouseMotionListener(new MouseMotionListener() {
            @Override
            public void mouseDragged(MouseEvent e) {
                if (!editable) {
                    return;
                }

                if (SwingUtilities.isLeftMouseButton(e)) {
                    // Dibuja el recuadro de selección
                    Graphics g = getGraphics();
                    getGraphics().drawImage(biImagen, 0, 0, null); // Dibuja la copia almacenada del fractal
                    g.setColor(Color.red); 
                    g.draw3DRect(mouseX, mouseY, e.getX() - mouseX, e.getY() - mouseY, false); 
                } else if (SwingUtilities.isRightMouseButton(e)) {
                    // Arrastra el contenido
                    int w = getSize().width;
                    int h = getSize().height;
                    viewX += (mouseX - e.getX()) / 16 * getZoom() / Math.min(w, h);
                    viewY += (mouseY - e.getY()) / 16 * getZoom() / Math.min(w, h);
                    repaint();
                }
            }

            @Override
            public void mouseMoved(MouseEvent e) {
            }
        });

        addMouseWheelListener(new MouseWheelListener() {
            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
                if (!editable) {
                    return;
                }
                int maxIteraciones = calculoFractal.getMaxIteraciones();
                maxIteraciones -= e.getWheelRotation();
                System.out.println(maxIteraciones);
                calculoFractal.setMaxIteraciones(maxIteraciones);
                repaint();

            }
        });
        
        this.setToolTipText("Hola");
    }

    /**
     * Genera una imagen de tipo BufferedImage con el zoom, punto x e y
     * que luego permite ser usado para almacenar en disco una copia, por ejemplo
     * @param ancho de la imagen a generar
     * @param alto de la imagen a generar
     * @return Imagen del fractal para ser almacenado en un fichero o base de datos
     */
    public BufferedImage generaImagen(int ancho, int alto) {
        BufferedImage imagenNueva = new BufferedImage(ancho, alto, BufferedImage.TYPE_INT_BGR);
        dibujaFractal(imagenNueva);
        return imagenNueva;

    }

    
    /**
     * Rutina de dibujado del control Fractal
     * @param g2 objeto para dibujar en este control
     */
    @Override
    public void paint(Graphics g2) {
        super.paint(g2);
        if (java.beans.Beans.isDesignTime()) {
            return;
        }

        long inicio = new Date().getTime();
        dibujaFractal(biImagen);
        long hasta = (new Date()).getTime();
        g2.drawImage(biImagen, 0, 0, null);
//        System.out.println("Ha tardado "+(hasta-inicio)+"ms");
//        System.out.println(this.getName()+ " : NumIter"+calculoFractal.getMaxIteraciones());

    }

    /**
     * Rutina interna que rellena la imagen con el fractal
     * @param img imagen donde dibujar el fractal
     */
    private void dibujaFractal(BufferedImage img) {
        int y, x;
        double dx;
        double dy;
        int value;
        Dimension size;
        double r;
        double offsetX = calculoFractal.getOffsetX();
        double offsetY = calculoFractal.getOffsetY();
        double factor = calculoFractal.getFactor();

        size = new Dimension(img.getWidth(), img.getHeight());
        r = getZoom() / Math.min(size.width, size.height);

        for (y = 0; y < size.height; y++) {
            for (x = 0; x < size.width; x++) {
                dx = factor * (x * r + getViewX()) - offsetX;
                dy = offsetY - factor * (y * r + getViewY());
                value = calculoFractal.calculaPunto(dx, dy);
                img.setRGB(x, y, colors[value % colors.length].getRGB());
            }
        }

    }
}
