/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cinthia
 */
public class VentanaAyuda extends javax.swing.JPanel {

    /**
     * Creates new form VentanaAyuda
     */
    public VentanaAyuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Curso soib de programación orientada a objetos\n----------------------------------------------\nArrastrar botón izquierdo: Hacer zoom \nArrastrar botón derecho: desplazar pantalla\nRueda ratón Añadir/Reducir número de iteraciones\nque es equivalente a añadir o quitar detalle\n\nOpciones de iconos:\nNuevo (Ctrl+N) -> \n Restaura a la situación inicial\n\nSelector de algoritmo -> \n Muestra un fractal diferente\n\nGuardar (Ctrl+S) -> \n Guarda un fichero JPG con la imagen actual\n\nAcceso a base de datos-> \n Necesita servicio de MySQL instalado\n Accede a la base de datos para recuperar puntos de interés\n Muestra una lista de puntos de interés almacenados en la BD\n\nAñadir punto de interés->\n Guarda en la base de datos un punto del fractal\n\nBorrar punto de interés-> \n Borra el punto\n\nF1 Ayuda ->\n Muestra esto\n");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
